FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack use pnpm@`pnpm -v`

FROM base AS build

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN pnpm add -g turbo@^2
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ARG APP_PORT=3042
ARG BASE_URL
ARG ES_URL
ARG DATABASE_URL
ARG DATABASE_AUTH_TOKEN
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG OG_SECRET
ARG LISTMONK_API_KEY
ARG LISTMONK_API_URL
ARG LISTMONK_FROM_EMAIL
ARG NEXT_PUBLIC_PLAUSIBLE_URL
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_POSTHOG_API_HOST
ARG NEXT_PUBLIC_POSTHOG_API_KEY
ARG NEXT_PUBLIC_POSTHOG_UI_HOST
ARG NEXT_PUBLIC_FORMBRICKS_API_HOST
ARG NEXT_PUBLIC_FORMBRICKS_ENV_ID
ARG NEXT_PUBLIC_CLOUDFLARE_HOST
ARG NEXT_PUBLIC_CLOUDFLARE_TOKEN
ARG NEXT_PUBLIC_OPENSTATUS_RUM_DSN
ARG API_SERVICES_TOKEN

ENV APP_PORT=${APP_PORT}
ENV BASE_URL=${BASE_URL}
ENV ES_URL=${ES_URL}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
ENV GOOGLE_ID=${GOOGLE_ID}
ENV GOOGLE_SECRET=${GOOGLE_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV OG_SECRET=${OG_SECRET}
ENV LISTMONK_API_KEY=${LISTMONK_API_KEY}
ENV LISTMONK_API_URL=${LISTMONK_API_URL}
ENV LISTMONK_FROM_EMAIL=${LISTMONK_FROM_EMAIL}
ENV NEXT_PUBLIC_PLAUSIBLE_URL=${NEXT_PUBLIC_PLAUSIBLE_URL}
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
ENV NEXT_PUBLIC_POSTHOG_API_KEY=${NEXT_PUBLIC_POSTHOG_API_KEY}
ENV NEXT_PUBLIC_POSTHOG_API_HOST=${NEXT_PUBLIC_POSTHOG_API_HOST}
ENV NEXT_PUBLIC_POSTHOG_UI_HOST=${NEXT_PUBLIC_POSTHOG_UI_HOST}
ENV NEXT_PUBLIC_FORMBRICKS_API_HOST=${NEXT_PUBLIC_FORMBRICKS_API_HOST}
ENV NEXT_PUBLIC_FORMBRICKS_ENV_ID=${NEXT_PUBLIC_FORMBRICKS_ENV_ID}
ENV NEXT_PUBLIC_CLOUDFLARE_HOST=${NEXT_PUBLIC_CLOUDFLARE_HOST}
ENV NEXT_PUBLIC_CLOUDFLARE_TOKEN=${NEXT_PUBLIC_CLOUDFLARE_TOKEN}
ENV NEXT_PUBLIC_OPENSTATUS_RUM_DSN=${NEXT_PUBLIC_OPENSTATUS_RUM_DSN}
ENV API_SERVICES_TOKEN=${API_SERVICES_TOKEN}

RUN pnpm run build

FROM base AS runner
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=build /app/apps/web/next.config.mjs .
COPY --from=build /app/apps/web/package.json .

COPY --from=build --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=build --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

ARG APP_PORT=3042
ARG BASE_URL
ARG ES_URL
ARG DATABASE_URL
ARG DATABASE_AUTH_TOKEN
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG OG_SECRET
ARG LISTMONK_API_KEY
ARG LISTMONK_API_URL
ARG LISTMONK_FROM_EMAIL
ARG NEXT_PUBLIC_PLAUSIBLE_URL
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_POSTHOG_API_HOST
ARG NEXT_PUBLIC_POSTHOG_API_KEY
ARG NEXT_PUBLIC_POSTHOG_UI_HOST
ARG NEXT_PUBLIC_FORMBRICKS_API_HOST
ARG NEXT_PUBLIC_FORMBRICKS_ENV_ID
ARG NEXT_PUBLIC_CLOUDFLARE_HOST
ARG NEXT_PUBLIC_CLOUDFLARE_TOKEN
ARG NEXT_PUBLIC_OPENSTATUS_RUM_DSN
ARG API_SERVICES_TOKEN

ENV APP_PORT=${APP_PORT}
ENV BASE_URL=${BASE_URL}
ENV ES_URL=${ES_URL}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
ENV GOOGLE_ID=${GOOGLE_ID}
ENV GOOGLE_SECRET=${GOOGLE_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV OG_SECRET=${OG_SECRET}
ENV LISTMONK_API_KEY=${LISTMONK_API_KEY}
ENV LISTMONK_API_URL=${LISTMONK_API_URL}
ENV LISTMONK_FROM_EMAIL=${LISTMONK_FROM_EMAIL}
ENV NEXT_PUBLIC_PLAUSIBLE_URL=${NEXT_PUBLIC_PLAUSIBLE_URL}
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
ENV NEXT_PUBLIC_POSTHOG_API_KEY=${NEXT_PUBLIC_POSTHOG_API_KEY}
ENV NEXT_PUBLIC_POSTHOG_API_HOST=${NEXT_PUBLIC_POSTHOG_API_HOST}
ENV NEXT_PUBLIC_POSTHOG_UI_HOST=${NEXT_PUBLIC_POSTHOG_UI_HOST}
ENV NEXT_PUBLIC_FORMBRICKS_API_HOST=${NEXT_PUBLIC_FORMBRICKS_API_HOST}
ENV NEXT_PUBLIC_FORMBRICKS_ENV_ID=${NEXT_PUBLIC_FORMBRICKS_ENV_ID}
ENV NEXT_PUBLIC_CLOUDFLARE_HOST=${NEXT_PUBLIC_CLOUDFLARE_HOST}
ENV NEXT_PUBLIC_CLOUDFLARE_TOKEN=${NEXT_PUBLIC_CLOUDFLARE_TOKEN}
ENV NEXT_PUBLIC_OPENSTATUS_RUM_DSN=${NEXT_PUBLIC_OPENSTATUS_RUM_DSN}
ENV API_SERVICES_TOKEN=${API_SERVICES_TOKEN}

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

CMD PORT=${APP_PORT} node apps/web/server.js