version: "3"

services: 
  sicap-ai:
    image: sicap-ai
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_URL: ${BASE_URL}
        ES_URL: ${ES_URL}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
        GOOGLE_ID: ${GOOGLE_ID}
        GOOGLE_SECRET: ${GOOGLE_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        OG_SECRET: ${OG_SECRET}
        LISTMONK_API_KEY: ${LISTMONK_API_KEY}
        LISTMONK_API_URL: ${LISTMONK_API_URL}
        LISTMONK_FROM_EMAIL: ${LISTMONK_FROM_EMAIL}
        NEXT_PUBLIC_PLAUSIBLE_URL: ${NEXT_PUBLIC_PLAUSIBLE_URL}
        NEXT_PUBLIC_PLAUSIBLE_DOMAIN: ${NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
        NEXT_PUBLIC_POSTHOG_API_KEY: ${NEXT_PUBLIC_POSTHOG_API_KEY}
        NEXT_PUBLIC_POSTHOG_API_HOST: ${NEXT_PUBLIC_POSTHOG_API_HOST}
        NEXT_PUBLIC_POSTHOG_UI_HOST: ${NEXT_PUBLIC_POSTHOG_UI_HOST}
        NEXT_PUBLIC_FORMBRICKS_API_HOST: ${NEXT_PUBLIC_FORMBRICKS_API_HOST}
        NEXT_PUBLIC_FORMBRICKS_ENV_ID: ${NEXT_PUBLIC_FORMBRICKS_ENV_ID}
        NEXT_PUBLIC_CLOUDFLARE_HOST: ${NEXT_PUBLIC_CLOUDFLARE_HOST}
        NEXT_PUBLIC_CLOUDFLARE_TOKEN: ${NEXT_PUBLIC_CLOUDFLARE_TOKEN}
        NEXT_PUBLIC_OPENSTATUS_RUM_DSN: ${NEXT_PUBLIC_OPENSTATUS_RUM_DSN}
        API_SERVICES_TOKEN: ${API_SERVICES_TOKEN}
