import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    ES_URL: z.string().url().optional().default("http://localhost:9200"),
    DATABASE_URL: z.string().url().optional().default("http://127.0.0.1:8080"),
    DATABASE_AUTH_TOKEN: z.string().optional().default("abcd"),
    GOOGLE_ID: z.string().optional(),
    GOOGLE_SECRET: z.string().optional(),
    AUTH_SECRET: z.string().optional().default("abcd"),
    NEXTAUTH_URL: z.string().url().optional().default("http://localhost:3000"),
    OG_SECRET: z.string().optional().default("abcd"),
    BASE_URL: z.string().url().optional().default("http://localhost:3000"),
    LISTMONK_API_KEY: z.string().optional(),
    LISTMONK_API_URL: z.string().url().optional().default("http://localhost:9000"),
    LISTMONK_FROM_EMAIL: z.string().email().optional(),
    API_SERVICES_TOKEN: z.string().optional().default(""),
  },
  client: {
    NEXT_PUBLIC_FORMBRICKS_API_HOST: z.string().min(1),
    NEXT_PUBLIC_FORMBRICKS_ENV_ID: z.string().min(1),
    NEXT_PUBLIC_POSTHOG_API_HOST: z.string().optional().default(""),
    NEXT_PUBLIC_POSTHOG_UI_HOST: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_API_KEY: z.string().optional().default(""),
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: z.string().optional().default(""),
    NEXT_PUBLIC_PLAUSIBLE_URL: z.string().optional().default(""),
    NEXT_PUBLIC_CLOUDFLARE_TOKEN: z.string().optional(),
    NEXT_PUBLIC_CLOUDFLARE_HOST: z.string().optional(),
    NEXT_PUBLIC_OPENSTATUS_RUM_DSN: z.string().optional().default(""),
    NEXT_PUBLIC_TELEMETRY_DISABLED: z.string().transform((s) => s !== "false" && s !== "0"),
  },
  runtimeEnv: {
    ES_URL: process.env.ES_URL,
    DATABASE_URL: process.env.DATABASE_URL,
    API_SERVICES_TOKEN: process.env.API_SERVICES_TOKEN,
    DATABASE_AUTH_TOKEN: process.env.DATABASE_AUTH_TOKEN,
    GOOGLE_ID: process.env.GOOGLE_ID,
    GOOGLE_SECRET: process.env.GOOGLE_SECRET,
    AUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    OG_SECRET: process.env.OG_SECRET,
    BASE_URL: process.env.BASE_URL,
    LISTMONK_API_KEY: process.env.LISTMONK_API_KEY,
    LISTMONK_API_URL: process.env.LISTMONK_API_URL,
    LISTMONK_FROM_EMAIL: process.env.LISTMONK_FROM_EMAIL,
    NEXT_PUBLIC_FORMBRICKS_API_HOST: process.env.NEXT_PUBLIC_FORMBRICKS_API_HOST,
    NEXT_PUBLIC_FORMBRICKS_ENV_ID: process.env.NEXT_PUBLIC_FORMBRICKS_ENV_ID,
    NEXT_PUBLIC_POSTHOG_API_HOST: process.env.NEXT_PUBLIC_POSTHOG_API_HOST,
    NEXT_PUBLIC_POSTHOG_UI_HOST: process.env.NEXT_PUBLIC_POSTHOG_UI_HOST,
    NEXT_PUBLIC_POSTHOG_API_KEY: process.env.NEXT_PUBLIC_POSTHOG_API_KEY,
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN,
    NEXT_PUBLIC_PLAUSIBLE_URL: process.env.NEXT_PUBLIC_PLAUSIBLE_URL,
    NEXT_PUBLIC_CLOUDFLARE_TOKEN: process.env.NEXT_PUBLIC_CLOUDFLARE_TOKEN,
    NEXT_PUBLIC_CLOUDFLARE_HOST: process.env.NEXT_PUBLIC_CLOUDFLARE_HOST,
    NEXT_PUBLIC_OPENSTATUS_RUM_DSN: process.env.NEXT_PUBLIC_OPENSTATUS_RUM_DSN,
    NEXT_PUBLIC_TELEMETRY_DISABLED: process.env.NEXT_PUBLIC_TELEMETRY_DISABLED,
  },
});
